site_name: LetTrade
site_url:
  !ENV [READTHEDOCS_CANONICAL_URL, "https://AwesomeTrading.github.io/LetTrade/"]
repo_url: https://github.com/AwesomeTrading/LetTrade
edit_uri: edit/develop/docs/
watch: [mkdocs.yml, README.md, lettrade, example]
use_directory_urls: True

nav:
  - Home: index.md
  - Install: install/
  - Tutorials: tutorial/
  - Indicator: indicator/
  - Development: dev.md
  - API reference:
      - LetTrade: reference/
      - SUMMARY: reference/SUMMARY.md
  # - FAQ: faq.md

theme:
  name: material
  logo: "image/logo.svg"
  favicon: "image/logo.svg"
  features:
    - content.code.annotate
    - search.share
    - content.code.copy
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

plugins:
  - search
  - autorefs
  - markdown-exec:
      ansi: required
  - gen-files:
      scripts:
        - docs/script/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://python-markdown.github.io/objects.inv
            - https://www.mkdocs.org/objects.inv
          paths: ["."]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["^lettrade", "example", "!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_requirejs: true
      allow_errors: false

extra_css:
  - css/mkdocstrings.css
  - css/jupyter.css

draft_docs: |
  draft/
  script/

markdown_extensions:
  - attr_list
  - admonition
  - callouts
  - footnotes
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
      base_path: [".", lettrade]
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AwesomeTrading/LetTrade
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/lettrade/
